site_name: Luigi Di Giacomo | Profile
site_url: https://luigidigiacomo.github.io/
site_author: Luigi Di Giacomo

theme:
  name: material       # oppure 'readthedocs' o 'mkdocs'
  language: it
  custom_dir: overrides

nav:
  - Home: index.md
  - Le mie esperienze: esperienze.md
  - I miei obiettivi: obiettivi.md
  - Altro: info.md
  
extra_css:
  - style.css
  - assets/stylesheets/extra.css

markdown_extensions:
  - attr_list