site_name: Luigi Di Giacomo | Portfolio
site_url: # ci stiamo lavorando
site_author: Luigi Di Giacomo

theme:
  name: material       # oppure 'readthedocs' o 'mkdocs'
  language: it
  favicon: assets/favicon.png

nav:
  - Home: index.md
  - Le mie esperienze: esperienze.md
  - I miei obiettivi: obiettivi.md
  - Altro: info.md

extra_css:
  - style.css
